PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX replaced_by: <http://purl.obolibrary.org/obo/IAO_0100001>

#this query is to find all the term which label contains special character(s)


SELECT distinct ?cls ?clslabel 
WHERE {
  {
  ?cls a owl:Class; 
      rdfs:label ?clslabel .
    
    FILTER (regex(str(?clslabel), "[^ +'.,A-Za-z0-9-_()\\[\\]]"))

    FILTER( !isBlank(?cls) && STRSTARTS(str(?cls), "http://purl.obolibrary.org/obo/VBO_"))
        
  }
    
} 